config/routes.rb
Zigna::Application.routes.draw do

  resources :messages

  root to: "pages#home"
  match 'services' => 'pages#services'
  match 'about' => "pages#about"
  match 'web_design' => "pages#web"
  match 'web_develop' => "pages#desarrollo"
  match 'web_grafic' => "pages#grafico"
  match 'image' => "pages#imagen"
  match 'multimedia'=> "pages#multimedia"
  match 'online' => "pages#online"
  match "mkt" => "pages#mkt"
  match "portfolio" => "pages#portfolio"
  match "contact" => "messages#new"
  match 'message' => 'messages#new', :as => 'message', :via => :get
  match 'message' => 'messages#create', :as => 'message', :via => :post

end

app/models/message.rb
class Message
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :nombre, :email, :asunto, :mensaje
 
  validates :nombre, :email, :asunto, :mensaje, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |nombre, value|
      send("#{nombre}=", value)
    end
  end

  def persisted?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
     
  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      # TODO send message here
      NotificationsMailer.new_message(@message).deliver
      flash[:success] = "Gracias por contactarnos."
      redirect_to contact_path
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end
end  

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home
	
end

def about
@titulo="NOSOTROS"	
end

def services
@titulo="SERVICIOS"
end

def contacto
@titulo="CONTACTO" 
end

def web
 respond_to do |format|
      format.js
      format.html
    end	
end

def desarrollo
 respond_to do |format|
      format.js
      format.html
    end	
end

def grafico
 respond_to do |format|
      format.js
      format.html
    end	
end

def imagen
 respond_to do |format|
      format.js
      format.html
    end	
end

def desarrollo
 respond_to do |format|
      format.js
      format.html
    end	
end

def multimedia
 respond_to do |format|
      format.js
      format.html
    end	
end

def mkt
 respond_to do |format|
      format.js
      format.html
    end	
end

def portfolio
  @titulo="PORTAFOLIO"
 respond_to do |format|
      format.js
      format.html
    end 
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer-menu.html.erb
<footer class="img-footer">
<ul class="menu menu-footer">
	<li><%= link_to "Home", root_path %></li>
	<li></div><%= link_to "Nosotros", about_path %></li>
	<li><%= link_to "Servicios" , services_path %></li>
	<li><%= link_to "Portafolio" , portfolio_path %></li>
	<li><%= link_to "Contacto" , contact_path %></li>
</ul>
<div class="container">
<p>© 2012 <%= link_to "Zigna Creativa", root_path %></p>
</div>
</footer>

app/views/layouts/_footer.html.erb
<%= link_to image_tag("button_top_footer.png" , :class => "button-footer") , "#telefono"%>

<footer class="foot">
<div class="container">
	<div class="section group">
		<div class="col span_1_of_3">
		<h3>Contáctanos</h3>
		<p>
			SM. 22 Retorno Azucenas #16</br>
			Teléfono: (998) 253.83.53</br>
			<a href="mailto:info@zignacreativa.com">info@zignacreativa.com</a>
		</p>
		</div>
		<div class="col span_1_of_3">
			<div class="tags">
				<h3>Tags</h3>
				<div class="half">
					<%= link_to "Diseño Web", services_path %><br>
					<%= link_to "Imagen Corporativa", services_path %><br>
					<%= link_to "Diseño Gráfico", services_path %><br>
				</div>
				<div class="half">
					<%= link_to "Marketing Online", services_path %><br>
					<%= link_to "Multimedia", services_path %><br>
					<%= link_to "CEO y SEM", services_path %><br>
				</div>
			</div>
		</div>
		<div class="col span_1_of_3">
			<div class="twitter-footer">
				<h3>Último tweet</h3>
				<% cache "twitter-footer#{Date.today}" do %>
				<%  t = Twitter.user_timeline("zignacreativa").first %>
				<div><h4>@<%= t.user.screen_name %></h4><%= t.text %><h4><%=  t.created_at.strftime("%I:%M %p") %></h4></div>
				<% end %>

			</div>
		</div>
	</div>
</div>
</footer>

app/views/layouts/_menu.html.erb
<div class="telefono" id="telefono"><%= image_tag("phone_zigna.png")%></div>
<header>
<%= link_to image_tag("header_logo.png") , root_path %>	
<ul class="menu">
	<li><div class="line-menu"></div><%= link_to "Home", root_path %></li>
	<li><div class="line-menu"></div><%= link_to "Nosotros", about_path %></li>
	<li><div class="line-menu"></div><%= link_to "Servicios", services_path %></li>
	<li><div class="line-menu"></div><%= link_to "Portafolio", portfolio_path %></li>
	<li> <%= link_to "Contacto", contact_path %></li>
</ul>
</div>
</header>

app/views/layouts/_socialmedia.html.erb
<div class="social-media">
<%=link_to image_tag("facebook.png"), "http://www.facebook.com/pages/Zigna-Creativa/174439495921568
", target: "_blank"%>
<%=link_to image_tag("twitter.png"), "http://twitter.com/zignacreativa" , target: "_blank"%>
<%=link_to image_tag("pinterest.png"), "http://pinterest.com/zignacreativa" , target: "_blank"%>
</div>

app/views/layouts/_styles.html.erb
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= favicon_link_tag 'favicon.ico' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zigna Creativa | Diseño Web</title>
  <%= render "layouts/styles" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">	
	<%= render "layouts/menu" %>
	<%= render "layouts/socialmedia"%>
</div>
<%= yield %>
<%= render "layouts/footer" %>
<%= render "layouts/footer-menu" %>
<%= javascript_include_tag "application" %>
</body>
</html>

app/views/messages/_form.html.erb
<div class="message">
  <p class="text">Si usted desea ponerse en contacto con nosotros para alguna cita o dejar un comentario 
llene los siguientes campos a continuación: 
</p>
<%= render "shared/alerts" %>
<%= form_for @message, :url => message_path do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :nombre , class: "form_text text" %><br />
    <%= f.text_field :nombre , class: "form_box" %>
  </div>
  <div class="field">
    <%= f.label :email , class: "form_text text" %><br />
    <%= f.text_field :email , class: "form_box" %>
  </div>
  <div class="field">
    <%= f.label :asunto , class: "form_text text" %><br />
    <%= f.text_field :asunto , class: "form_box" %>
  </div>
  <div class="field">
    <%= f.label :mensaje , class: "form_text text" %><br />
    <%= f.text_area :mensaje , class: "form_textarea" %>
  </div>
  <div class="actions">
    <%= f.submit "Enviar" , class: "form_botton"%>
  </div>
<% end %>
</div>

app/views/messages/new.html.erb
<%= render "pages/header"%>
<div class="container">
	<div class="services">
		<h1 class="title">Contáctanos</h1>
		<div class="line line-short line-about-big"></div>
		<%= render 'form' %>
	<div class="contacto">
		<p class="text"><span>Horario de Oficina</span></br>Lunes-Viernes: 9:00 a.m - 6:00 p.m </p>
		<div class="contacto-img">
		<%= image_tag("icon_phone.png") %>
		<p class="text contacto-text"> Fijo (998) 253.83.53</br>
			Nextel 62*1042090*2
		</p>
		</div>
		<div class="contacto-img">
		<%= image_tag("icon_email.png") %>
		<div><p class="text contacto-text">
		info@zignacreativa.com
		</p></div>
		</div>
		<div class="contacto-img">
		<%= image_tag("icon_adress.png") %>
		<p class="text contacto-text">
		SM. 22 Retorno Azucenas #16 C.P. 77500
		</p>
		</div>


	</div>
</div>
</div>

app/views/pages/_center_about.html.erb
<div class="center_about">
	<h1 class="title">Quiénes Somos</h1>
	<div class="line line-short"></div>
	<p class="text text-about">
	Profesionales creativos en busca de la mejor solución para tu
proyecto. Conformamos una firma fresca y auténtica especializada que traduce tus necesidades al  lenguaje del desarrollo y diseño web, multimedia, diseño
gráfico, Marketing online, y un sinfín de posibilidades.</p>
	<h1 class="title">Como lo Hacemos:</h1>
	<div class="line line-short"></div>
	<div class="column_left">
	<p class="column text">
	<span>1. Percibir</br></span>
	Observar, escuchar y sentir las necesidades de nuestro cliente y así trazar el objetivo.
	</p>
	<p class="column text">
	<span>3. Desarrollar</br></span>
	Aplicamos lo analizado para generar agentes de cambio que desarrollen su concepto.
	</p>
	</div>

	<div class="column_right">
	<p class="column text">
	<span>2. Analizar</br></span>
	Comparar el entorno del mercado y de la competencia, aprovechando las fortalezas y debilidades del cliente, para ofrecerle las mejores soluciones a su proyecto.
	</p>
	<p class="column text">
	<span>4. La mejor experiencia de trabajo</br></span>
	Con base a tu satisfacción garantizamos los mejores resultados que tus necesidades requiera.
	</p>
	</div>
</div>

app/views/pages/_servicios.html.erb
<div id="ca-container" class="ca-container">
<div class="ca-nav">
	<span class="ca-nav-prev">Previous</span>
	<span class="ca-nav-next">Next</span>
</div>
	<div class="ca-wrapper">
		<!-- Contenido del carrucel -->
		<div class="ca-item">
			<div class="ca-item-main">
				<div class="ca-icon"><%= image_tag("dg-services.png") %></div>
					<h3>Diseño</br> Gráfico</h3>
						<h4>
						<div class="dash_line"><%= image_tag("dashline_services.png") %></div>
						<span>Creamos soluciones visualmente atractivas ofreciendo un diseño creativo y funcional capaz de llegar al mercado al que va dirigido.</span>
					</h4>
						<%= link_to "Ver Más", services_path , :class => "more" %>
				</div>			
			</div>
			
		<div class="ca-item">
			<div class="ca-item-main">
				<div class="ca-icon"><%= image_tag("webdesign_services.png") %></div>
					<h3>Diseño <br/> Web</h3>
						<h4>
						<div class="dash_line"><%= image_tag("dashline_services.png") %></div>
						<span>
						Te ofrecemos soluciones Web personalizadas completamente a tu medida.Empleamos las tecnologías más actuales, para diseñar y desarrollar sitios web atractivos.
						</span>
					</h4>
						<%= link_to "Ver Más", services_path , :class => "more" %>
				</div>			
		</div>

		<div class="ca-item">
			<div class="ca-item-main">
				<div class="ca-icon"><%= image_tag("mkt_services.png") %></div>
					<h3>Marketing </br> Online</h3>
						<h4>
						<div class="dash_line"><%= image_tag("dashline_services.png") %></div>
						<span>
Existen nuevas herramientas en internet es por eso que desarrollamos estrategias de marketing personalizadas.</span>
					</h4>
						<%= link_to "Ver Más", services_path , :class => "more" %>
				</div>			
		</div>


		<div class="ca-item">
			<div class="ca-item-main">
				<div class="ca-icon"><%= image_tag("sistemas-services.png") %></div>
					<h3>Sistemas </br> Web</h3>
						<h4>
						<div class="dash_line"><%= image_tag("dashline_services.png") %></div>
						<span>Digitalizamos y Automatizamos tus procesos, te ayudamos a que ahorres tiempo, dinero y controles con exactitud tu negocio.</span>
					</h4>
						<%= link_to "Ver Más", services_path , :class => "more" %>
				</div>			
		</div>

		<div class="ca-item">
			<div class="ca-item-main">
				<div class="ca-icon"><%= image_tag("coporative-services.png") %></div>
					<h3>Imagen </br> Corporativa</h3>
						<h4>
						<div class="dash_line"><%= image_tag("dashline_services.png") %></div>
						<span>Creamos la identidad corporativa de su empresa de manera que se pueda reflejar cada elemento comunicativo con precisión.</span>
					</h4>
						<%= link_to "Ver Más", services_path , :class => "more" %>
				</div>			
		</div>
 
<div class="ca-item">
			<div class="ca-item-main">
				<div class="ca-icon"><%= image_tag("multimedia.png") %></div>
					<h3>Proyectos</br>Multimedia</h3>
						<h4>
						<div class="dash_line"><%= image_tag("dashline_services.png") %></div>
						<span>Llevamos tu imagen a medios interactivos. En donde cada elemento gráfico se exprese en movimiento.</span>
					</h4>
						<%= link_to "Ver Más", services_path , :class => "more" %>
				</div>			
		</div>




		<!-- fin del contenido -->
	</div>
</div>

app/views/pages/_slide.html.erb
<div id="da-slider" class="da-slider">
				<div class="da-slide">
					<h2 class="header-gray">Diseño<div class="header-white">Web</div></h2>
					<p>Diseño y Desarrollo Web adaptado a tus necesidades. Aportamos las mejores soluciones para tu proyecto web.</p>
					<div class="da-img"><%= link_to image_tag("web_services_header.png") %></div>
					<%= link_to "Ver Ahora" ,  services_path , :class => 'da-link' %>
				</div>
				<div class="da-slide">
					<h2 class="header-gray">Posicionamiento
					 <div class="header-white">Web</div></h2>
					<p>Coloca el nombre de tu empresa en los primeros lugares de los buscadores (google, yahoo) y expande tu marca en la web.</p>
					<div class="da-img"><%= link_to image_tag("mkt_services_header.png") %></div>
					<%= link_to "Ver Ahora" ,  services_path , :class => 'da-link' %>
				</div>
				<div class="da-slide">
					<h2 class="header-gray">Imagen
					 <div class="header-white">Corporativa</div></h2>
					<p>Creamos la identidad corporativa de tu empresa logrando reflejar cada elemento comunicativo con precisión.</p>
					<div class="da-img"><%= link_to image_tag("imagen-corp.png") %></div>
					<%= link_to "Ver Ahora" ,  services_path , :class => 'da-link' %>
				</div>
				<div class="da-slide">
					<h2 class="header-gray">Cómo
					 <div class="header-white">Lo Hacemos</div></h2>
					<p>Los tres elementos básicos que al combinarlos producen la mejor experiencia de trabajo PERCIBIR , ANALIZAR y DESARROLLAR. </p>
					<div class="da-img"><%= link_to image_tag("brain_home.png") %></div>
					<%= link_to "Ver Ahora" ,  about_path , :class => 'da-link' %>
				</div>
				<nav class="da-arrows">
					<span class="da-arrows-prev"></span>
					<span class="da-arrows-next"></span>
				</nav>
			</div>
        </div>

app/views/pages/about.html.erb
<%= render "header"%>
<div class="container">
	<div class="brain"><%=image_tag("brain_nosotros.png")%></div>
	<%= render "center_about"%>
</div>

app/views/pages/desarrollo.js.erb
$(document).ready(function() {
$('.content').empty();
$('.content').html("<%= escape_javascript render(:file => 'pages/desarrollo', :formats => [:html])  %>");    
$('.develop').addClass("active").removeClass("botton-service");
$('.services-menu ul li a').not('.develop').addClass("botton-service").removeClass("actvive");
});

app/views/pages/grafico.html.erb
<div class="service-title"><h1 class="title">Diseño Gráfico</h1></div>
<p class="frase">
Proyectar y realizar una acción gráficamente comunicativa es importante a la hora de desarrollar tu proyecto correctamente. 
</p></br>
<p class="text">
Creamos soluciones visualmente atractivas ofreciendo un diseño creativo y funcional capaz de llegar al mercado al que va dirigido y comunicar el de manera eficaz el mensaje con el máximo impacto.
</p>
<p class="text">
Los servicios que manejamos para diseño gráfico son:
</p>
<p class="text">
<ul class="text text-service">
	<li>Diseño Publicitario</li>
	<li>Brochure</li>
	<li>Revista</li>
	<li>Material Gráfico</li>
	<li>Prensa</li>
	<li>Promocional</li>
	<li>Ilustración</li>
	<li>Exteriores</li>
</ul>
</p>

app/views/pages/grafico.js.erb
$(document).ready(function() {
$('.content').empty();
$('.content').html("<%= escape_javascript render(:file => 'pages/grafico', :formats => [:html])  %>");    
$('.grafico').addClass("active").removeClass("botton-service");
$('.services-menu ul li a').not('.grafico').addClass("botton-service").removeClass("actvive");
});

app/views/pages/home.html.erb
<%= render "slide" %>
<div class="container">
<%= render "lateral" %>
<%= render "center" %> 
</div>
<%= render "servicios" %>

app/views/pages/imagen.html.erb
<div class="service-title"><h1 class="title">Imagen Corporativa</h1></div>
<p class="frase">
Creamos la identidad corporativa de su empresa de manera que se pueda reflejar cada elemento comunicativo con precisión.
</p></br>
<p class="text">La imagen de tu empresa es importante, es por eso que nos enfocamos en desarrollar un logotipo a si como sus variantes en aplicaciones gráficas, también entregamos un manual corporativo donde vienen todas las especificaciones de uso.
</p></br>

<p class="text">Los servicios que manejamos para imagen corporativa son:
</p>

<p class="text">
<ul class="text text-service">
	<li>
   Diseño de Logotipo</li>
   <li>Manual Corporativo</li>
	<li>Diseño de Papeleria</li>
	<li>Aplicaciones Gráficas</li>
	<li>Naming.</li>
</ul>
</p>

app/views/pages/imagen.js.erb
$(document).ready(function() {
$('.content').empty();
$('.content').html("<%= escape_javascript render(:file => 'pages/imagen', :formats => [:html])  %>");    
$('.imagen').addClass("active").removeClass("botton-service");
$('.services-menu ul li a').not('.imagen').addClass("botton-service").removeClass("actvive");
});

app/views/pages/multimedia.js.erb
$(document).ready(function() {
$('.content').empty();
$('.content').html("<%= escape_javascript render(:file => 'pages/multimedia', :formats => [:html])  %>");    
$('.multimedia').addClass("active").removeClass("botton-service");
$('.services-menu ul li a').not('.multimedia').addClass("botton-service").removeClass("actvive");
});

app/views/pages/online.js.erb
$(document).ready(function() {
$('.content').empty();
$('.content').html("<%= escape_javascript render(:file => 'pages/online', :formats => [:html])  %>");    
$('.online').addClass("active").removeClass("botton-service");
$('.services-menu ul li a').not('.online').addClass("botton-service").removeClass("actvive");
});

app/views/pages/portfolio.html.erb
<%= render "header"%>
<div class="container">
	<div class="services">
<h1 class="title">Muestras Gráficas</h1>
		<div class="line line-short line-about-big"></div>
<section>
				<ul id="da-thumbs" class="da-thumbs">
					<li>
							<%= link_to asset_path("1-full.jpg")  , class: "fancy"   do  %>
							<%= image_tag("1.jpg") %>
							<div><span>Imagen Corporativa</span></div>
							<% end %>
					</li>

					<li>
							<%= link_to asset_path("2-full.jpg")  , class: "fancy"   do  %>
							<%= image_tag("2.jpg") %>
							<div><span>Imagen Corporativa</span></div>
							<% end %>
					</li>

					<li>
							<%= link_to asset_path("3-full.jpg")  , class: "fancy"   do  %>
							<%= image_tag("3.jpg") %>
							<div><span>Pieza Gráfica</span></div>
							<% end %>
					</li>

					<li>
							<%= link_to asset_path("4-full.jpg")  , class: "fancy"   do  %>
							<%= image_tag("4.jpg") %>
							<div><span>Pieza Gráfica</span></div>
							<% end %>
					</li>

					<li>
							<%= link_to asset_path("5.swf")  , class: "fancy"  do  %>
							<%= image_tag("5.jpg") %>
							<div><span>Banner Interactivo</span></div>
							<% end %>
					</li>

					<li>
							<%= link_to asset_path("6-full.jpg")  , class: "fancy"   do  %>
							<%= image_tag("6.jpg") %>
							<div><span>Pieza Gráfica</span></div>
							<% end %>
					</li>

					<li>
							<%= link_to asset_path("7-full.jpg")  , class: "fancy"   do  %>
							<%= image_tag("7.jpg") %>
							<div><span>Proyecto Web</span></div>
							<% end %>
					</li>
				</ul>
			</section>
		</div>
	</div>

app/views/pages/web.js.erb
$(document).ready(function() {
$('.content').empty();
$('.content').html("<%= escape_javascript render(:file => 'pages/web', :formats => [:html])  %>");    
$('.web').addClass("active").removeClass("botton-service");
$('.services-menu ul li a').not('.web').addClass("botton-service").removeClass("actvive");
});

app/views/shared/_alerts.html.erb
<% flash.each do |key, value| %>
<div class="flash-<%= key %> ">
<%= value %>
</div>
<% end %>